### ISSUE TITLE
add a block remote cmd

### ISSUE THREAD

**Issue by joshclark756** [fatesc/fates-admin#62]
**Is your feature request related to a problem? Please describe.**
blockremote or remote block can block a certain remote 

**Describe the solution you'd like**
ability to block remotes

**Comment by NotDSF** [comment]
This command would be quite useless to the average fates admin user, if you're smart enough to get remotes then you should at least know how to block them? I think this would be quite a challenge and a useless command due to you having to type in the path etc.. so I would recommend https://github.com/Upbolt/Hydroxide instead which can provide all these features + more

**Comment by NotDSF** [comment]
Also if you would really want this then make a [plugin](https://github.com/fatesc/fates-admin/wiki/Plugins) but the above comment is purely my opinion and you will have to wait for fates opinion on it

**Comment by fatesc** [comment]
will not be added
