### ISSUE TITLE
Crashing on scriptware MAC OS never had a problem

### ISSUE THREAD

**Issue by confine16** [fatesc/fates-admin#77]
When the script loads, everything Is fine until it says something about a hook and config, which initiates the crash

**Comment by NotDSF** [comment]
Please provide a screenshot

**Comment by niglet-x** [comment]
same here it full on crashes a second after fates loads

**Comment by fatesc** [comment]
scriptware mac has always had issues loading fates admin, this is the exploits problem. You could try and report it to the sw-m dev but i doubt he would fix it as people have already been reporting this for months

**Comment by scrptuser** [comment]
Ik I'm late, but yeah I'm also having an issue w/ script ware, I'm pretty sure the reason for the not injecting part is relates to the new update; roblox loading in the same window, instead of a different window. If roblox were loaded into a diff window, it would load fine, but bc of the new roblox update, script ware hasn't adapted to it yet
